### ISSUE TITLE
trigger change after populating input fields

### ISSUE THREAD

**Issue by matthiaswagnerwy** [Hube2/acf-dynamic-ajax-select-example#5]
i built a script upon your dynamic-select-example. it populates a select-field depending on another select field. in addition, i have acf conditional logic which depends on the populated field. for this to work, i had to add a line in dynamic-select-example/my-acf-extension.js:70

$select.change();

so acf recognizes that something has changed here and updates the conditional logic.

**Comment by Hube2** [comment]
Glad you found my examples useful for your project
